<div style="font-family: Arial, Helvetica, sans-serif; font-size: 0.95rem">
    <b>{{ $headline }}</b>
    <p>
        {!! $body !!}
    </p>
    <br>
    <br>
    <hr>
    <b>This is an automated message sent from the Computer Aided Dispatch system.</b><br>
    It was generated by {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} on {{ Carbon\Carbon::now()->toRfc822String() }}.
</div>